# Example YAML config for image_analysis.py

# Notes for config fields:
# use_multiple_models: Boolean. If true, every model listed in 'models' will be run sequentially and per-model outputs recorded.
#   If false, only the first model in the 'models' array will be used.
# models: Array of model names (strings). Example: ['gemma3:12b', 'gemma2'].
#   Include model identifiers and optional size/version as appropriate.
# prompt_desc: Short description or instruction passed to the model. Can be a concise instruction or a pointer to a full prompt template.
#   This can be overridden via CLI when running the script.
# input: Path to the input file (Excel or CSV) containing rows to analyze (e.g., ./data/text_input/abstracts.xlsx).
# output: Path to the output Excel file where results and metadata will be written (e.g., ./data/text_output/abstracts_results.xlsx).
# id_col: Name of the column in the input file that uniquely identifies each row (e.g., "id").
# content_col: Name of the column that contains the text to analyze (e.g., "abstract").
# runs: Integer. Number of replicate runs per input row to capture model variability. Use 1 for a single run. Adjust runs and consensus settings to balance reproducibility and runtime.
# consensus: Boolean. Whether to compute a consensus value across replicate runs for each row.
# consensus_mode: One of 'exact', 'set', or 'fuzzy'. Controls how consensus is determined:
#   - exact: responses must match exactly.
#   - set: treat responses as unordered sets of tokens/labels (order-independent comparison).
#   - fuzzy: group responses by similarity using fuzzy matching.
# fuzzy_threshold: Integer 0-100. Controls sensitivity for fuzzy grouping (higher = stricter/more similar required).
#   Only used when consensus_mode is 'fuzzy'.
# delay: Float. Seconds to wait between switching models when running multiple models sequentially. Use 0.0 for no delay.

use_multiple_models: true
models:
  - 'gemma3:12b'
  - 'llava:13b'
  - 'llama3.2-vision:11b'

# short human-readable description of what to extract
prompt_desc: "three criteria for evaluating the design in the image"

# Windows paths should be quoted to avoid YAML escape issues
input: 'C:\\Users\\leves\\OneDrive - University of Cincinnati\\LLM images for analysis\\Input with all images'
output: 'C:\\Users\\leves\\OneDrive - University of Cincinnati\\LLM images for analysis\\output with all images'

runs: 10

within-model-consensus: true
within-model-consensus-mode: fuzzy
within-model-fuzzy-threshold: 85

between-model-consensus: true
between-model-consensus-mode: fuzzy
between-model-fuzzy-threshold: 85

delay: 0.5
append-metadata: true