# Example YAML config for text_analysis.py
# Use 'use_multiple_models' to control single vs multiple model runs.
# YAML supports comments, so this file is easier for humans to edit.

_notes: "Example YAML config for text_analysis.py. Provide models as an array."
use_multiple_models: false
models:
  - gemma3:12b
prompt_desc: "Main topic to extract from each row's content. Can be a short instruction or pointer to a full prompt template."
input: "./data/text_input/abstracts.xlsx"
output: "./data/text_output/abstracts_results.xlsx"
id_col: "id"
content_col: "abstract"
runs: 3
consensus: true
consensus_mode: fuzzy
fuzzy_threshold: 85
delay: 0.0

_field_descriptions:
  use_multiple_models: "Boolean. If true, every model listed in 'models' will be run sequentially and per-model outputs recorded. If false, only the first model in the 'models' array will be used."
  models: "Array of model names (strings). Example: ['gemma3:12b', 'gemma2']"
  prompt_desc: "Short description or instruction passed to the model. Override via CLI if needed."
  input: "Path to input Excel/CSV file for the text workflow."
  output: "Output Excel file where results and metadata will be written."
  runs: "Integer: number of replicate runs per input row to capture variability."
  consensus: "Boolean: whether to compute a consensus value per model."
  consensus_mode: "One of 'exact', 'set', or 'fuzzy'. See README for differences."
  fuzzy_threshold: "Integer 0-100 controlling fuzzy grouping sensitivity (higher = stricter)."
  delay: "Seconds to wait between switching models when running multiple models sequentially."
